const plantData = [
    {name: "Aglaonema (Chinese evergreen)"},
    {name: "Alocasia"},
    {name: "Anthurium"},
    {name: "Aphelandra squarrosa (zebra plant)"},
    {name: "Araucaria heterophylla (Norfolk Island pine)"},
    {name: "Asparagus aethiopicus (asparagus fern)"},
    {name: "Aspidistra elatior (cast iron plant)"},
    {name: "Begonia"},
    {name: "Bromeliaceae (bromeliads)"},
    {name: "Calathea (prayer plants)"},
    {name: "Chamaedorea elegans (parlor palm)"},
    {name: "Dypsis lutescens (areca palm)"},
    {name: "Chlorophytum comosum (spider plant)"},
    {name: "Citrus"},
    {name: "Cyclamen"},
    {name: "Dracaena"},
    {name: "Dieffenbachia (dumbcane)"},
    {name: "Epipremnum aureum (golden pothos)"},
    {name: "Ficus benjamina (weeping fig)"},
    {name: "Ficus elastica (rubber plant)"},
    {name: "Ficus lyrata (fiddle-leaf fig)"},
    {name: "Hippeastrum"},
    {name: "Hoya"},
    {name: "Mimosa pudica"},
    {name: "Nephrolepis exaltata (Boston fern)"},
    {name: "Orchidaceae (orchids)"},
    {name: "Peperomia"},
    {name: "Philodendron "},
    {name: "Maranta (prayer plant)"},
    {name: "Monstera (Swiss cheese plant)"},
    {name: "Sansevieria trifasciata (mother-inlaw's tongue)"},
    {name: "Schefflera arboricola (umbrella plant)"},
    {name: "Sinningia speciosa (gloxinia)"},
    {name: "Spathiphyllum (peace lily)"},
    {name: "Stephanotis floribunda (Madagascar jasmine)"},
    {name: "Streptocarpus (African violets)"},
    {name: "Tradescantia zebrina (purple wandering Jew)"},
    {name: "Pilea peperomioides"},
    {name: "Scindapsus pictus (satin pothos)"},
    {name: "Yucca"},
    {name: "Aloe vera"},
    {name: "Cactaceae (cacti)"},
    {name: "Epiphyllum (orchid cacti)"},
    {name: "Opuntia"},
    {name: "Zygocactus (Christmas cactus)"},
    {name: "Gymnocalycium mihanovichii (chin cactus)"},
    {name: "Crassula ovata (jade plant)"},
    {name: "Echeveria"},
    {name: "Haworthia"},
    {name: "Senecio angulatus (creeping groundsel)"},
    {name: "Senecio rowleyanus (string of pearls)"},
    {name: "Tillandsia xerographica"},
    {name: "Tillandsia ionantha"},
    {name: "Tillandsia bulbosa"},
    {name: "Tillandsia caput medusae"},
    {name: "Crocus"},
    {name: "Hyacinthus (hyacinth)"},
    {name: "Narcissus"},
    {name: "Hedera helix (English ivy)"},
    {name: "Saxifraga stolonifera (strawberry begonia)"}, 
 ]
 
